name: 'Python S3 Upload Action'
description: 'Upload files to an S3-compatible bucket using Python'
inputs:
  endpoint_url: 
    description : 'URL of the S3-compatible endpoint'
    required: true
  key_id: 
    description : 'AWS access key ID'
    required: true
  application_key: 
    description : 'AWS secret access key'
    required: true
  file: 
    description : 'File pattern to upload'
    required: true
  destination: 
    description : 'Destination directory in bucket'
    required: true
  bucket: 
    description : 'Destination bucket name'
    required: true
runs:
using: "composite"
steps:
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: "3.10"

  - name: Install dependencies
    run: |
      pip install -r requirements.txt

  - name: Run the Python script
    run: |
      python main.py --endpoint_url ${{ inputs.endpoint_url }} --key_id ${{ inputs.key_id }} --application_key ${{ inputs.application_key }} --file ${{ inputs.file }} --destination ${{ inputs.destination }} --bucket ${{ inputs.bucket }}